
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'mariusteor/web-app-devops-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Marius Radu DevOps(161bfef5-9068-4f3e-aed0-0bc8905e7672)'
    azureResourceGroup: 'aks-resources'
    kubernetesCluster: 'flask-app-deployment'
    manifests: 'application-manifest.yaml'